In [12]:
'''
Create two 3×3 matrices using the random function in Numpy and perform the following operations.
-> Product (prod)
-> Multiplication (multiply)
-> Dot Product (dot)
'''
import numpy as np
matrix1=np.random.randint(1,5,size=(3,3))
matrix2=np.random.randint(1,5,size=(3,3))

print("MAT 1 :\n",matrix1)
print("MAT 2 :\n",matrix2)

prodMatrix=np.prod([matrix1,matrix2])
multiplyMatrix=np.multiply(matrix1,matrix2)
dotProductMatrix=np.dot(matrix1,matrix2)

print("Product Matrix\n",prodMatrix,"\n")
print("Multiply Matrix\n",multiplyMatrix,"\n")
print("Dot Product Matrix\n",dotProductMatrix)


MAT 1 :
 [[2 2 4]
 [3 3 4]
 [4 1 4]]
MAT 2 :
 [[2 3 4]
 [3 2 2]
 [1 4 4]]
Product Matrix
 42467328 

Multiply Matrix
 [[ 4  6 16]
 [ 9  6  8]
 [ 4  4 16]] 

Dot Product Matrix
 [[14 26 28]
 [19 31 34]
 [15 30 34]]


In [11]:
'''
Perform the following set operations using the Numpy functions.
-> Union
-> Intersection
-> Set difference
-> XOR
'''
arr1=np.array([1,3,2,5,6,8])
arr2=np.array([7,3,4,5,2,9])

union_arr=np.union1d(arr1,arr2)
intersection_arr=np.intersect1d(arr1,arr2)
diffrence_arr=np.setdiff1d(arr1,arr2)
print("Union Array\n",union_arr,"\n")
print("Intersection Array\n",intersection_arr,"\n")
print("Diffrence Array\n",diffrence_arr)

Union Array
 [1 2 3 4 5 6 7 8 9] 

Intersection Array
 [2 3 5] 

Diffrence Array
 [1 6 8]


In [14]:
'''
Create a 1D array using Random function and perform the following operations.
-> Cumulative sum
-> Cumulative Product
-> Discrete difference (with n=3)
-> Find the unique elements from the array
'''
arr=np.random.randint(1,5,size=(10))
cumsum = np.cumsum(arr)
cumprod = np.cumprod(arr)
discdiff = np.diff(arr,n=3)
uniqueElements = np.unique(arr)
print("Cumulative Sum\n",cumsum,"\n")
print("Cumulative Product \n",cumprod,"\n")
print("Discrete Difference\n",discdiff,"\n")
print("Unique Elements\n",uniqueElements)

Cumulative Sum
 [ 3  4  5  8 12 15 19 20 23 25] 

Cumulative Product 
 [   3    3    3    9   36  108  432  432 1296 2592] 

Discrete Difference
 [ 0 -3 -1  4 -6  9 -8] 

Unique Elements
 [1 2 3 4]


In [5]:
''' 
Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())
'''
import numpy as np
arr1=np.random.randint(1,5,size=(10))
arr2=np.random.randint(2,7,size=(10))
zipsum=zip(arr1,arr2)
addsum=np.add(arr1,arr2)

def add(a,b):
    return a+b
addfunc = np.frompyfunc(add,2,1)
addfuncresult=addfunc(arr1,arr2)

print("Zip() Method")
for i in zipsum:
    print(i," ")
print("\nAdd() method :\n",addsum,"\n")
print("frompyfunc() method :\n",addfuncresult,"\n")

Zip() Method
(1, 5)  
(1, 6)  
(4, 6)  
(1, 2)  
(4, 2)  
(3, 5)  
(4, 2)  
(4, 3)  
(4, 6)  
(2, 3)  

Add() method :
 [ 6  7 10  3  6  8  6  7 10  5] 

frompyfunc() method :
 [6 7 10 3 6 8 6 7 10 5] 



In [2]:
''' 
Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().
'''
import numpy as np
arr=np.random.randint(1,5,size=(10))
LCM = np.lcm.reduce(arr)
GCD = np.gcd.reduce(arr)
print("LCM : ",LCM)
print("GCD : ",GCD)

LCM :  12
GCD :  1
