In [1]:
"""Write a program to distinguish between Array Indexing and Fancy Indexing."""
import numpy as np
arr = np.array((20,40,29,48,71,63))
print("Array Indexing")
print("3rd Element is ",arr[2])
print("6rd Element is ",arr[5])
print("\nFancy Indexing")
condition=arr>20
filterElements=arr[condition]
print("Elements greater than 20 ",filterElements)
customIndices=[1,5]
filterElements=arr[customIndices]
print("Elements with Custom Indices ",filterElements)

Array Indexing
3rd Element is  29
6rd Element is  63

Fancy Indexing
Elements greater than 20  [40 29 48 71 63]
Elements with Custom Indices  [40 63]


In [5]:
"""Execute the 2D array Slicing."""
import numpy as np
arr= np.array([[3,5,6,3,9,5,7,1],[34,54,12,39,92,5,45,78],[4,5,6,3,6,3,3,2]])
sr = arr[0:2]
sc = arr[:,2:4]
print("Elements of First 2 Rows\n",sr)
print("\nElements of Third and Fourth Colomn of All Rows\n",sc)




Elements of First 2 Rows
 [[ 3  5  6  3  9  5  7  1]
 [34 54 12 39 92  5 45 78]]

Elements of Third and Fourth Colomn of All Rows
 [[ 6  3]
 [12 39]
 [ 6  3]]


In [1]:
"""Create the 5-Dimensional arrays using ‘ndmin’."""
import numpy as np
arr = np.array([[2,3,4,5],[4,3,9]],ndmin=5)

print(arr)

[[[[[list([2, 3, 4, 5]) list([4, 3, 9])]]]]]


C:\Users\aravi\AppData\Local\Temp\ipykernel_5892\316500152.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[2,3,4,5],[4,3,9]],ndmin=5)


In [12]:
"""Reshape the array from 1-D to 2-D array."""
import numpy as np
arr = np.array([43, 23, 64, 45, 21, 78, 90, 98, 23, 41])
newarr = arr.reshape(5, 2)
print(newarr)

[[43 23]
 [64 45]
 [21 78]
 [90 98]
 [23 41]]


In [9]:
"""Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack()."""
import numpy as np
arr1 = np.array([[2,3,4,5],[4,3,9,5]])
arr2 = np.array([[13,12,56,78],[89,23,90,87]])

stack= np.stack((arr1,arr2))
hstack=np.hstack((arr1,arr2))
vstack=np.vstack=((arr1,arr2))
dstack=np.dstack((arr1,arr2))

print("Stacking:\n",stack)
print("\nVertical  Stacking:\n",vstack)
print("\nHorizontal  Stacking:\n",hstack)
print("\nDepth  Stacking:\n",dstack)


Stacking:
 [[[ 2  3  4  5]
  [ 4  3  9  5]]

 [[13 12 56 78]
  [89 23 90 87]]]

Vertical  Stacking:
 (array([[2, 3, 4, 5],
       [4, 3, 9, 5]]), array([[13, 12, 56, 78],
       [89, 23, 90, 87]]))

Horizontal  Stacking:
 [[ 2  3  4  5 13 12 56 78]
 [ 4  3  9  5 89 23 90 87]]

Depth  Stacking:
 [[[ 2 13]
  [ 3 12]
  [ 4 56]
  [ 5 78]]

 [[ 4 89]
  [ 3 23]
  [ 9 90]
  [ 5 87]]]


In [3]:
"""Perform the searchsort method in Numpy array."""
import numpy as np
arr = np.array([43, 23, 64, 45, 21, 78, 90, 98, 23, 41])
arr = np.sort(arr)
print("Given Array ",arr)
newnum = input("Enter Number to insert")
sortedarr = np.searchsorted(arr,newnum) 
print(newnum," should be in position ",sortedarr)


Given Array  [21 23 23 41 43 45 64 78 90 98]
45  should be in position  5


In [2]:
"""Create Numpy Structured array using your domain features."""
import numpy as np
dtype=np.dtype([('workerId','U10'),('workerName','U20'),('workerAge','i4'),('hourlyRate','i4'),('rating','i4'),('averageDuration','i4'),('location','U10')])
data=np.array([
    ('W1','Vivek Gupta','28',220,4.2,7,'Patna'),
    ('W10','Olivia Martin','24',200,4.3,10,'New York'),
    ('W21','William','20',160,4.0,8,'California'),
    ('W5','Rebecca Turner','22',210,4.9,6,'New Jearsy'),
    ('W1','Madhav Menon','25',205,4.4,6,'Brooklyn'),
     ],dtype=dtype)
print(data)


[('W1', 'Vivek Gupta', 28, 220, 4,  7, 'Patna')
 ('W10', 'Olivia Martin', 24, 200, 4, 10, 'New York')
 ('W21', 'William', 20, 160, 4,  8, 'California')
 ('W5', 'Rebecca Turner', 22, 210, 4,  6, 'New Jearsy')
 ('W1', 'Madhav Menon', 25, 205, 4,  6, 'Brooklyn')]


In [2]:
"""Create Data frame using List and Dictionary."""
import pandas as pd
dict1={
    'name':["Samantha","Tom","John","Serah"],
    'age':[23,24,21,25],
    'gender':["Female","Male","Male","Female"]
}
df = pd.DataFrame(dict1)
#df = pd.DataFrame.from_dict(dict1)
print(df)



       name  age  gender
0  Samantha   23  Female
1       Tom   24    Male
2      John   21    Male
3     Serah   25  Female


In [15]:
"""Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()
"""
import pandas as pd 
data=pd.read_csv("LaborData.csv")
df= pd.DataFrame(data)
print("Original Data Frame")
print(df)

print("To Check Null Data")
print(df.isnull())

print("To Check NotNull Data")
print(df.notnull())

print("Dropping Rows with Null datas")
dropped_df=df.dropna()
print(dropped_df)

print("Filling Rows with Null datas")
filled_df=df.fillna({'workerId':'W0','workerName':'Dummy Worker','workerAge':25,'hourlyRate':200,'rating':4,'averageDuration':10,'location':'India'})
print(filled_df)

print("Replace To specific Data John Doe to Johnny")
replace_df=df.replace('John Doe','Johnny')
print(replace_df)

print("Interpolate Data")
interpolated_df=df.interpolate()
print(interpolated_df)





Original Data Frame
   workerId       workerName  workerAge  hourlyRate  rating  averageDuration   
0        W1         John Doe        NaN        20.0     4.5              6.0  \
1        W2       Jane Smith       30.0        18.0     4.7              5.0   
2        W3  Michael Johnson       27.0        22.0     4.2              7.0   
3        W4      Alice Brown       29.0        25.0     NaN              6.0   
4        W5     David Wilson        NaN        20.0     4.6              6.0   
..      ...              ...        ...         ...     ...              ...   
95      W96       Neha Yadav       32.0       220.0     4.5              NaN   
96      W97      Rahul Verma       28.0       250.0     4.7              5.0   
97      W98     Sneha Sharma       30.0         NaN     4.2              7.0   
98      W99  Abhishek Tiwari       27.0       200.0     4.9              6.0   
99     W100      Kirti Singh       29.0       210.0     NaN              6.0   

         location  

In [17]:
"""Perform the Hierarchical Indexing in the above created dataset."""
import pandas as pd 
data=pd.read_csv("LaborData.csv")
df= pd.DataFrame(data)
print("Original Data Frame")
print(df)
df.set_index(['workerId','location'])
print("Dataframe with Hierarchical Indexing")
print(df)

Original Data Frame
   workerId       workerName  workerAge  hourlyRate  rating  averageDuration   
0        W1         John Doe        NaN        20.0     4.5              6.0  \
1        W2       Jane Smith       30.0        18.0     4.7              5.0   
2        W3  Michael Johnson       27.0        22.0     4.2              7.0   
3        W4      Alice Brown       29.0        25.0     NaN              6.0   
4        W5     David Wilson        NaN        20.0     4.6              6.0   
..      ...              ...        ...         ...     ...              ...   
95      W96       Neha Yadav       32.0       220.0     4.5              NaN   
96      W97      Rahul Verma       28.0       250.0     4.7              5.0   
97      W98     Sneha Sharma       30.0         NaN     4.2              7.0   
98      W99  Abhishek Tiwari       27.0       200.0     4.9              6.0   
99     W100      Kirti Singh       29.0       210.0     NaN              6.0   

         location  